version: '3.8'

services:
  postgresql:
    image: postgres:10-stretch
    container_name: pg-docker
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_sample
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always

  pgadmin:
    image: dpage/pgadmin4:5.7
    container_name: pg-admin
    ports:
      - "8085:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=username@contoso.com
      - PGADMIN_DEFAULT_PASSWORD=password

  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8084:80"